### ISSUE TITLE
`--config` doesn't work in Windows

### ISSUE THREAD

**Issue by hone** [heroku/plugin-container-build#4]
Running `$ heroku local:build --config` in windows runs into this problem when trying to build the env dir layer:

```
COPY failed: stat /var/lib/docker/tmp/docker-builder806846994/env: no such file or directory
```

I believe this is because tar pathing behaves potentially different on windows, so docker can't find the env dir.

**Comment by jkutner** [comment]
This was fixed somewhere along the way.
